"""create weather forecast table

Revision ID: eb84beacee7a
Revises: 
Create Date: 2026-05-23 17:18:36.419086

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eb84beacee7a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('weather_forecast',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('forecast_date', sa.Date(), nullable=False),
    sa.Column('temperature_max', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('temperature_min', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('precipitation_sum', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('relative_humidity_2m_max', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_weather_forecast_slug'), 'weather_forecast', ['slug'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_weather_forecast_slug'), table_name='weather_forecast')
    op.drop_table('weather_forecast')
    # ### end Alembic commands ###
